### ISSUE TITLE
Fantomas V

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#2160]
## Introduction

Over the years Fantomas has been improving, making it usable in more and more codebases. Under the hood, we still do a lot of questionable processing to reconstruct the correct code. It is well known that we use the FSharp Compiler Services to collect our information via the Untyped Abstract Syntax Tree (AST). Alas, we don't always have enough information in the tree and so we resort to finding answers in the F# tokens. 

Going forward, we wish to improve the syntax tree so that we can have a more streamlined codebase and have better performance.
Pull requests for this over `dotnet/fsharp` have been submitted in the past and eventually make it into `FCS`.
This process works but is time-consuming. The releases of FCS are scarce and unpredictable. There are no hard feelings here, but we wish to explore an alternative way of integrating the compiler in Fantomas.

This issue serves as a meta issue to collect the various aspects of the next major version.
Not everything is known at this point, and what is known can be subjected to change.

### Core goals

In essence, the theme of the next major version is having a better syntax tree. And we need to make some fundamental (and potentially breaking) changes to get there. We want to improve the syntax tree on `dotnet/fsharp` side and eat our cake on Fantomas side shortly afterwards.

### Community goals

Next to our core goals, we also wish to provide a stage where the community can address https://github.com/fsprojects/fantomas/issues/1408. This setting still has open questions and we wish to engage the community to pick this up as part of version five.

### Breaking changes

A major version allows for breaking changes. We will address certain topics, that we otherwise couldn't due to semantic versioning.
Of course, with a focus on keeping the impact for end-users to a minimum.

### Change

- [x] We would no longer use the FCS NuGet package and grab the F# compiler from the source files instead, https://github.com/fsprojects/fantomas/issues/2217
- [x] Revisit the Elmish settings as part of the community goals, https://github.com/fsprojects/fantomas/issues/2180
- [x] Rename `Fantomas` to `Fantomas.Core` and `fantomas-tool` to `fantomas`, https://github.com/fsprojects/fantomas/issues/2174
- [x] Move to `net6`, https://github.com/fsprojects/fantomas/issues/2172
### Deprecate

- [x] Remove `fsharp_semicolon_at_end_of_line`, https://github.com/fsprojects/fantomas/issues/2247
- [x] Remove `fsharp_keep_if_then_in_same_line`, https://github.com/fsprojects/fantomas/issues/2248
- [x] Remove `fsharp_indent_on_try_with`, https://github.com/fsprojects/fantomas/issues/2249
- [x] Revisit all command line tool setting: consider removing `--stdin`, `--stdout`, https://github.com/fsprojects/fantomas/issues/2346
- [x] `Fantomas.Extras` (we might introduce a separate package that exposes the `.editorconfig` to `FormatConfig` parsing), https://github.com/fsprojects/fantomas/issues/2269

### Add
- [X] Setting `fsharp_stroustrup_style` (name to be discussed in https://github.com/fsprojects/fantomas/issues/1408)

## Technical process

All development is now happening on the master branch.

**Comment by Smaug123** [comment]
Could you please clarify what "grab the F# compiler from the source files instead" means?  I don't think I follow; surely you don't mean compiling the F# compiler from source as part of Fantomas?

**Comment by nojaf** [comment]
Hi there,

> surely you don't mean compiling the F# compiler from source as part of Fantomas

Actually, I do mean that, but it is less bad than it sounds.
I'm working on a [prototype](https://github.com/nojaf/fantomas/tree/embedded-fcs) where I take the relevant source files from the compiler via Paket. We will create our [own little FCS layer](https://github.com/nojaf/fantomas/blob/embedded-fcs/src/Fantomas.FCS/Fantomas.FCS.fsproj) and only exposes lexing and parsing.

Any [recent improvements](https://github.com/dotnet/fsharp/pulls?q=is%3Apr+12843+12854) that are made in the compiler can be picked up immediately by moving the git commit pointer in the [paket.dependencies](https://github.com/nojaf/fantomas/blob/embedded-fcs/paket.dependencies#L23-L99) file.

The footprint of our own compiler service is significantly less compared with the full FCS on NuGet.
So, this will benefit performance and most important it will drive us to fix/improve more things on the parser side.

There is some more prose in the [documentation folder](https://github.com/nojaf/fantomas/blob/embedded-fcs/docs/Fantomas-V.md) where I elaborate a bit more. Though some parts are already outdated.

Let me know if you have any further questions.

**Comment by alfonsogarciacaro** [comment]
For reference Fable has a similar situation, we use a custom build of the FCS compiler based on a [fork maintained by @ncave](https://github.com/ncave/fsharp/pull/2) to improve the performance of incremental compilation with Fable. It's probably not the best way to do things but this is how we do it:

- We try to keep the changes to a minimum so there're no conflicts when syncing the fork with the origin
- Removing the FCS parts that are not needed by Fable is not a goal right now
- We don't keep FCS sources in Fable repo, just a binary build. This build has to be referenced from all dependent .fsproj files
- Atm updating is not automated. Whenever there are changes I just build manually the fork and [copy the .dlls to Fable repos](https://github.com/fable-compiler/Fable/tree/34837bda02e8a51a1cfae35456539c11739eeceb/lib/fcs)

Again, this is just for reference in case it helps, probably Fantomas' needs require a different process. Also, please note that this is different from building the Fable Repl which uses yet another fork 😸 in a totally different way (it does remove files, sources are kept in Fable repo and CI builds it every time)>
