### ISSUE TITLE
Fantomas VI

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#2709]
## Introduction

In the aftermath of ["Project Dallas"](https://blog.nojaf.com/2022/12/22/the-oak-sleeps-in-the-acorn/) some new opportunities have surfaced for Fantomas. The Oak model could have appeal in the larger F# community. And it makes it possible to expand more on [Stroustrup](https://github.com/fsprojects/fantomas/issues/1408) functionality.

In order to seize all these opportunities we have decided to announce a new major release for 2023. This removes any restrictions and allows us to tune the public API to facilitate everything.

We kicked off this conversation during one of our "talk to the developers" sessions on your [Discord server](https://discord.gg/D5QXvQrBVa). We encourage you to join this server if you haven't already. Keep an eye out for events in the `#announcements` channel.

### Goals

We would like to expose the [SyntaxOak](https://fsprojects.github.io/fantomas/reference/fantomas-core-syntaxoak.html) module and provide new endpoints to format an `Oak` and parse an `Oak` from a string.

Next, we wish to expand on Stroustrup functionality by introducing a bit more granularity. Currently, Stroupstrup is an all-or-nothing situation. To a limited degree, we wish to split up some of the existing functionality.

Lastly, we wish to introduce some auxiliary features that will improve your overall Fantomas experience.

### Breaking changes

The `Fantomas.Core` API will break and the `.editorconfig` will no longer be compatible with the `5.x` series. In practice, not that much will change. (It will really depend on your use case). We wish to keep the changes to a minimum and provide everybody with a smooth upgrade.

### Change

- [ ] Introduce a verbosity flag to control the console output. https://github.com/fsprojects/fantomas/issues/2627
- [ ] Update Stroustrup style to be in sync with the [style guide proposal](https://github.com/dotnet/docs/pull/33171).
- [ ] Exclude computation expression from Stroustrup. https://github.com/fsprojects/fantomas/issues/2276
- [ ] Introduce a separate setting for Stroupstrup in function applications ending with one or two collection expression arguments.
- [ ] Introduce a separate setting for Stroupstrup in function applications ending with a record expression.
- [ ] Update long patterns. https://github.com/fsharp/fslang-design/issues/647
- [ ] Parallel formatting. https://github.com/fsprojects/fantomas/issues/2624

### Deprecate

- [ ] In https://github.com/fsprojects/fantomas/pull/2658, we solidified the setting to control multiline record syntax. `fsharp_multiline_block_brackets_on_same_column` and `fsharp_experimental_stroustrup_style` would be removed. Going forward, only `fsharp_multiline_bracket_style` shall be accepted. Please note that `fsharp_multiline_bracket_style` is available from `5.2` onward.

### Add

- [ ] Expose SyntaxOak API.
- [ ] Marker API. When formatting source code programmatically you can insert a marker (range) and after formatting, we can tell you where that marker would be in the formatted code. This would be useful for editors to position the cursor after formatting.

## Technical process

The plan is to do all the development on a separate `v6` branch. 
Bugfixing `v5.2` would still happen on `main`. 

//cc @dawedawe @josh-degraw @TheAngryByrd @edgarfgp
