### ISSUE TITLE
Using `--check` gives error "todo WhileBang"

### ISSUE THREAD

**Issue by abelbraaksma** [fsprojects/fantomas#3019]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAzAFAJRgC8YWAhgM4DWYwAOgE4MB2EET2Ark%2B1k26JmbAL4jWEzDgDmRUuWp1GLdhwDuACwCWmAIR558WGAAOTbayy52DSFkRUslmeUfPWMuxNGQANOBQVNgeMlSoYADagRCgHByQACRYAJ6myGiQllj%2BMQmJAG4U6EIR0fHxAAwBFQkAkqxIVgDK2gBeyDW1YAAseRAAunmiXbH9UMlpGVDZubVJRSXT5d0AjKMVkACyFAAeADKWiPuInliac2sATJXjQ-EjeXGbk%2BkRkKfwAPK4h6yIzVSmEu8QWxVKaBWtSuG1BAFFGj8-p1xhBIOhcJA7sMNs9Qa9ppAAEawWDoEH5RYQqKosAAZlh9VYwSYWAAYpZigA5RDqdBHCnxARCbEPXHjJKpN6ZElkwUTKnLWk9Rlo5qmCjQRAAIUQuFgXAAChQmBQALbYRBMeUQYWIUUcR7xPH5KWE2XkxlgpZlWkAVlVUHVmp1eoNx1g6it0GoiAaBVgMecsFYNvIgnttXujvF8wJ7w98u91KhFQAbIHIMGtbr9VwAKqmdJMGPBeOJijJ1OB3DFYIOiBOjgutH5mWkz0SwrgpXdMAAdkr1dDdcQAGF0NQqGuU05BNAsAa0730P2szinlO3QWJ0Xpz7IbSABxLjU1sNcLaIM1Eq3HvuZhU2aDrmLzXuOcpeveJa0gAnK%2BIa1uGO7oCm-6noB8TAWAQ5jHm4FQIWUGKr6c6rNUtJVm%2BiAAIK4A4TA7maZoUGmdoDjhoH4gRxK3sRM6kWs6yUcuSFcM037aHAqHdrSJ5nkBF7OleUw3pBU4kY%2BZEwiJ1F0QxElmlJZJoYG7HnmKl74apEGTnmmk0mRDK6SGNFMLA3CNAAIog-JGQxbEZhxuH0Cp0ozFYd4OaW8SrCqlE7LsdS4AAKpopzNJoBpYAA6to8DnGmtwWTmVlgTZEU5PxD6OWsAYJXsyVpaccIYZl2V5QVFyBmWxWKZZynWeFWSRdVMFkRWDVJawuDaLsXzNp2Bpwrs5iOFQ2imc%2BfVYUpw5hYSsxjbOayLlNABKiBwEw8CdYVgY9DtHDYSFI4TDxR0aQJWlrC%2BF1XQa8BctwP5Wj8dQOGa4SBqswVca6FWQGa3DoM4-L-GyBosVgDEpapx2CbUqzwZRl3XfAWwo2jRyY0w2MBZW0CaCamoMQA%2Buo%2BWFXDZXcYjn32d9tXQhRc7bHsbmmikXxMIcTh3d12084N5XDQLLzRbSVzCWLiWSxQ0uy9oTjA6DTDg5D0O0rDJUgbzCPDcjqO6DTWOdrj%2BNfTVMUcFcOli-rhty1glPO%2BjiC0-Tf6M8zpoHlaHNcxcyv7UNh2jV743dFczm63sABqM7apY8AuAraZPk9gx7Xhqvp1VmcndC8V57sbKeQem2sMXjRl0naaPSntd82rGeC97Wv1a3XmwFgADi2ArWtVAbSm5eBpXQ%2BhWnal2RrQs%2BxAVyTWLPJ8kcupYFGpx4%2BkPmzaw2hdjRjRfmbVtzuZ-WlSrI-unxjdCYVCuGdAO-IZCsHbqwTuKZWgQM7LwRAKVYANCaJQLs6EFK7QGqnOuu8ooHy1n9MBDFWCdm0AUCMng36-iYPfSwT8u4f26PJTCz0a7bzwbZAhE85xXBJrrKm2hkT7HNESeAFANywA2p4M%2B4dMFsOrjg4eDt-7qXHlnWodJRbdEgEvK02gLRWGKAAaUQIgUwqDThYAaNqU00DFZzlYVvN6kpEZEUAT9LROtdHak3KwGgyIqBuQ8o0HkThEAUyEeHJeXAV5MMCiKW2nF7ajh4h4jRTcKh0n9r4k0YlEBeWNtACwRkyEOHgPWR%2BKYfLQE3KaDBPYAIuIOu8J21N-h2M1DQbAgIUjAgJl47JuddGhw6TqOOPSsB9IGZREp5p0jwCxMk16rTMjq3xJrOcdIW66LMRYxKptaE-D8RQAJQS0zkSrmAF68M0nuIAZkoB8Q6RT10XIi%2BH5EBjJdv8JiphuDoK7rE9aXdEmKJuRw1xY5CKPP3rw7odIT66P0aU6xxRWpGSoI4lhzSVmBAGF0LIVA2QbQiM40QQA)

#### Code

```fsharp
let f() = task {
    return true
}

let g() = task {
    while! f() do printfn "testing testing"
}
```
            

#### Result (note: this is expected!)

```fsharp
let f () = task { return true }

let g () =
    task {
        while! f () do
            printfn "testing testing"
    }

```
            
#### Problem description

Having something like the above, actually prevents the formatting and when running:

```
dotnet fantomas . --check
```

raises the following exception:

```text
error: Failed to format .\src\FSharp.Control.TaskSeq\TaskSeqInternal.fs: System.Exception: todo for WhileBang
  (Yes (656,20--656,44),
   App
     (Atomic, false,
      LongIdent
        (false,
         SynLongIdent ([e; MoveNextAsync], [(656,28--656,29)], [None; None]),
         None, (656,27--656,42)), Const (Unit, (656,42--656,44)),
      (656,27--656,44)),
   YieldOrReturn
     ((true, false),
      LongIdent
        (false, SynLongIdent ([e; Current], [(657,31--657,32)], [None; None]),
         None, (657,30--657,39)), (657,24--657,39)), (656,20--657,39))
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1439.Invoke(String message) in D:\a\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1439
   at Fantomas.Core.ASTTransformer.collectComputationExpressionStatements(CreationAide creationAide, SynExpr e, FSharpFunc`2 finalContinuation) in /_//src/Fantomas.Core/ASTTransformer.fs:line 345
   at Fantomas.Core.ASTTransformer.mkExpr(CreationAide creationAide, SynExpr e) in /_//src/Fantomas.Core/ASTTransformer.fs:line 1123
   at Fantomas.Core.ASTTransformer.mkExpr(CreationAide creationAide, SynExpr e) in /_//src/Fantomas.Core/ASTTransformer.fs:line 1108
   at Fantomas.Core.ASTTransformer.mkExpr(CreationAide creationAide, SynExpr e) in /_//src/Fantomas.Core/ASTTransformer.fs:line 1384
   at Fantomas.Core.ASTTransformer.mkSynMatchClause(CreationAide creationAide, SynMatchClause _arg4) in /_//src/Fantomas.Core/ASTTransformer.fs:line 376
   at Fantomas.Core.ASTTransformer.mkExpr@1147-8.Invoke(SynMatchClause arg10@)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x) in D:\a\_work\1\s\src\fsharp\FSharp.Core\local.fs:line 246
   at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list) in D:\a\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 74
   at Fantomas.Core.ASTTransformer.mkExpr(CreationAide creationAide, SynExpr e) in /_//src/Fantomas.Core/ASTTransformer.fs:line 1143
   at Fantomas.Core.ASTTransformer.collectComputationExpressionStatements(CreationAide creationAide, SynExpr e, FSharpFunc`2 finalContinuation) in /_//src/Fantomas.Core/ASTTransformer.fs:line 345
   at Fantomas.Core.ASTTransformer.mkExpr(CreationAide creationAide, SynExpr e) in /_//src/Fantomas.Core/ASTTransformer.fs:line 1123
   at Fantomas.Core.ASTTransformer.mkBinding(CreationAide creationAide, SynBinding _arg7) in /_//src/Fantomas.Core/ASTTransformer.fs:line 1810
   at Fantomas.Core.ASTTransformer.mkModuleDecl(CreationAide creationAide, SynModuleDecl decl) in /_//src/Fantomas.Core/ASTTransformer.fs:line 1971
   at Fantomas.Core.ASTTransformer.mkModuleDecls@3074-5.Invoke(FSharpList`1 nodes) in /_//src/Fantomas.Core/ASTTransformer.fs:line 3074
   at Fantomas.Core.ASTTransformer.mkModuleDecl(CreationAide creationAide, SynModuleDecl decl) in /_//src/Fantomas.Core/ASTTransformer.fs:line 1982
   at Fantomas.Core.ASTTransformer.mkModuleDecls@3074-5.Invoke(FSharpList`1 nodes) in /_//src/Fantomas.Core/ASTTransformer.fs:line 3074
   at Fantomas.Core.ASTTransformer.mkModuleOrNamespace(CreationAide creationAide, SynModuleOrNamespace mn) in /_//src/Fantomas.Core/ASTTransformer.fs:line 3139
   at Fantomas.Core.ASTTransformer.mds@3149.Invoke(SynModuleOrNamespace mn)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x) in D:\a\_work\1\s\src\fsharp\FSharp.Core\local.fs:line 244
   at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list) in D:\a\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 74
   at Fantomas.Core.ASTTransformer.mkImplFile(CreationAide creationAide, ParsedImplFileInput _arg15, Range m) in /_//src/Fantomas.Core/ASTTransformer.fs:line 3149
   at Fantomas.Core.ASTTransformer.mkOak(FSharpOption`1 sourceText, ParsedInput ast) in /_//src/Fantomas.Core/ASTTransformer.fs:line 3574
   at Fantomas.Core.CodeFormatterImpl.formatAST(ParsedInput ast, FSharpOption`1 sourceText, FormatConfig config, FSharpOption`1 cursor) in /_//src/Fantomas.Core/CodeFormatterImpl.fs:line 66
   at Fantomas.Core.CodeFormatterImpl.formatDocument@89-3.Invoke(Unit unitVar) in /_//src/Fantomas.Core/CodeFormatterImpl.fs:line 89
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 446
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
.\src\FSharp.Control.TaskSeq\TaskSeqInternal.fs needs formatting
```

I wonder if the "todo" can be ignored somehow. It also seems like work has been done already, as the online tool shows it is formatted without error, so maybe I just have to be patient (but reporting anyway in case someone else encounters this).

Appreciate all the good work as always!!! It is also sooo much faster than, say, a year ago! 

#### Extra information

- [ ] The formatted result breaks my code.
- [x] The formatted result gives tool errors.
- [x] I or my company would be willing to help fix this.
- [x] I would like a release if this problem is solved (it breaks the pipeline)

Live example: https://github.com/fsprojects/FSharp.Control.TaskSeq/actions/runs/7256774972/job/19769562682?pr=209

**Comment by nojaf** [comment]
Hi there,

`'6.2.3` does not support `while!`, it was introduced in https://github.com/fsprojects/fantomas/blob/main/CHANGELOG.md#630-alpha-002---2023-11-07

**Comment by abelbraaksma** [comment]
Great stuff! I missed it somehow in the changelog. I'll wait for next version :).

**Comment by dawedawe** [comment]
> Great stuff! I missed it somehow in the changelog. I'll wait for next version :).

Or give the alpha a spin ;)
You will most likely find it very stable already.

**Comment by abelbraaksma** [comment]
I thought about that, but I couldn't find docs how to download the alpha in CI (i.e., `dotnet tools update` does not seem to pick up alpha versions, even if I specify them). @dawedawe do you know how? And/or where there's instruction to do so?

**Comment by abelbraaksma** [comment]
I would need to update these lines somehow, I guess, or the manifest file: https://github.com/fsprojects/FSharp.Control.TaskSeq/blob/b08c257e5513b9dcc700dc55740858b96f2d7570/.github/workflows/build.yaml#L6

**Comment by dawedawe** [comment]
What happens if you do a
`dotnet tool update fantomas --prerelease` ?
That should give you a
`"version": "6.3.0-alpha-004",`
inside of the manifest.

**Comment by abelbraaksma** [comment]
Ah, that "just works", awesome! (online there was the suggestion to use `--version "*-alpha*"` which did not work for me and I didn't look beyond that).

Thanks for the help 🙇.

**Comment by bartelink** [comment]
small aside - if you use the format `6.3.0-alpha.4`, i.e. with a dot instead of a dash, each piece between periods is treated as a number from the point of view of sorting and hence doesn't need prefixing (yes, there are stone age versions of nuget that don't respect that, but they are long gone.)

**Comment by nojaf** [comment]
No thanks
