### ISSUE TITLE
Fantomas v4.0

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#705]
## Introduction

As more and more feature requests are leaning in the way of breaking changes, it is time to consider the development of the next major version. This issue serves as a placeholder to keep track of the issues that will introduce breaking changes.

This release would initially not contain very impactful changes. However, if you would format with the last 3.x versus 4.0, the output would be slightly different in some scenarios.

## In scope

- [x] Sunset setting `ReorderOpenDeclaration` #645
- [x] Sunset setting `KeepNewlineAfter` #737
- [x] Simplify Feature: space between function and unit #649
The idea here would be to remove the current opinionated way of adding a space based on lowercase/uppercase/unit or parenthesis rules. The outcome would introduce less settings as currently mentioned in the PR.
- [x] Record on single line setting #697
- [x] Deprecate all the CLI settings regarding style configuration #704
- [x] Support the [G-Research F# code formatting guidelines](https://github.com/G-Research/fsharp-formatting-conventions)
- [x] Update documentation #725

## Considerations

- Remove MakePos and MakeRange from public API
- Consider new names and/or default values for settings. No concrete plan at the moment, but the next major gives us that luxury.
